// Code generated by sopher (https://github.com/hyperproperties/sopher). DO NOT EDIT.
package main

import (
	sopher "github.com/hyperproperties/sopher/pkg/language"
	"testing"
)

func Test_pin_Check_0_hpcontract(t *testing.T) {
	runner := sopher.NewTestRunner(Check_0_Call, Check_0_Contract)
	runner.N(100)
	runner.Run(t)
}
